# HEADER: This will call all the processes from here.
# There are other make files, but this one handles them.



# ___ For testing 

test:
	$(info The UNIX build environment was set up successfully.)



# ___ For build environment

osfloppy:
	cd Compilation/On_Linux && $(MAKE) Boot_Setup.flp